#!/usr/bin/env python3
import json, os
base = json.load(open('eval/baseline_metrics.json'))
curp = 'eval/model_metrics.json'
cur = json.load(open(curp)) if os.path.exists(curp) else None

def row(name, r, b=None):
    return f"| {name} | {r.get('summarization',{}).get('rougeL_f_mean','—')} | {r.get('summarization',{}).get('bertscore_f1_mean','—')} | {r.get('sentiment',{}).get('macro_f1','—')} | — | — | in:0.05/out:0.15 | — |"

print('### Metrics (autogenerated)\n')
print('| Variant | ROUGE-L(F) | BERTScore F1 | Macro-F1 (sent) | p50 ms | p95 ms | Cost/1k toks (¢) | Notes |')
print('|---|---:|---:|---:|---:|---:|---:|---|')
print(row('Baseline (Lead-3, VADER)', base))
if cur:
    print(row('Model v1 (gpt-5-mini@sum_v1, distilbert@sent_v2)', cur))
